### ISSUE TITLE
A bug😎

### ISSUE THREAD

**Issue by Mydak2281** [j-red/LethalCompany-RemoveMotionSway#3]
So when you first time start game it will be normal but after you leave lobby and join again the visor will spawn and it will be insane buggy😱😱

**Comment by j-red** [comment]
Noted! Seems like something must have changed with the last update. For now it appears that relaunching your game should resolve the issue (until you leave the lobby and join again), but I'll add this to the list of things to fix. Thanks for reporting it!

**Comment by Mydak2281** [comment]
ok👍

**Comment by j-red** [comment]
Believe this is resolved as of v1.2.0, which should be available on Thunderstore shortly! It's also available in the Releases tab here on GitHub. I wasn't able to test too exhaustively, but from the few random lobbies I joined it does appear to be fixed. Let me know if there are any issues with it you run into!
