### ISSUE TITLE
Leave and rejoin bug

### ISSUE THREAD

**Issue by FireNinja7365** [j-red/LethalCompany-RemoveMotionSway#4]
when first loading into a world after starting the game it works fine, but if i leave the world and then rejoin it breaks and the model for the mask starts rendering again and it's kinda janky, it could be a mod conflict, but the only other mods im using that effect visuals are HDcompany, and fullbright, ¯\_(ツ)_/¯ anyhow i hope you fix it

**Comment by j-red** [comment]
Probably the same issue as #3, it's on my list! For now the workaround is to completely restart the game before rejoining a new lobby, will hopefully get to fixing it soon.

**Comment by j-red** [comment]
Resolved as of release v1.2.0, should be available on Thunderstore shortly!
