### ISSUE TITLE
Incompatible with other fov adjust mods

### ISSUE THREAD

**Issue by jms8719** [j-red/LethalCompany-RemoveMotionSway#5]
I'm unable to change fov with other mods when this mod is active.
It's not a bug, but do you think this could be changed? I'm guessing this has to do with the fixed POV while sprinting.

**Comment by j-red** [comment]
Totally, that seems like a good call! I'll see about adding a configuration option to disable the FOV lock so you can disable this for mod compatibility. Thanks for the suggestion!

**Comment by j-red** [comment]
Just pushed an update to Thunderstore to add a Config setting for the mod, allowing you to disable the FOV lock or set it to a specific value. It should be available there shortly! [https://thunderstore.io/c/lethal-company/p/kz/RemoveMotionSway/](https://thunderstore.io/c/lethal-company/p/kz/RemoveMotionSway/)
