### ISSUE TITLE
Motion Sway Intensity

### ISSUE THREAD

**Issue by PantsBanditUSA** [j-red/LethalCompany-RemoveMotionSway#6]
Would there be a way to do a motion sway intensity config instead of straight up removing it? I am actually trying to increase my motion sway so I can make it look like I have body cam footage.

**Comment by j-red** [comment]
This seems super doable, yeah! Here's a quick mockup of a 3x intensity, does [this](https://youtu.be/sf2ddVbC2pM) look like what you're wanting? And would you need the mask overlay to sell the effect too? (the logic for it was annoying to program around so I just removed it, lol, but could probably add it back)

**Comment by j-red** [comment]
Implemented as of v.1.2.1, available on the releases tab (the cache on Thunderstore should update in a few hours)! You'll need to run the game once to generate the new config files, then set `Disable Motion Sway` to `false` and change the value of the `Motion Sway Intensity` option to something higher than 1.0 (I'd recommend 3?). Curious to hear if this fits what you're looking for!

**Comment by j-red** [comment]
Woops, published the wrong .dll for v.1.2.1 release. This feature is properly implemented as of v.1.2.2, available on the releases tab or on Thunderstore in a few hours (whenever their cache updates).
