### ISSUE TITLE
Config option for motion sway

### ISSUE THREAD

**Issue by welles** [j-red/LethalCompany-RemoveMotionSway#7]
Hi there! Very nice mod! I've been looking for a mod that remove the visor and lets you change the FOV.
Could you add a config option to re-enable motion sway though? I know it's ironic because of the mod's name, but it's actually the one thing we'd like to keep enabled in our game. 😄

**Comment by j-red** [comment]
Thank you very much! Yes, I've actually just implemented this feature (latest release v1.2.2), which allows you to re-enable and control the intensity of the motion sway via configuration options. It should be available on Thunderstore in a few hours or via the Releases tab for the project; you'll need to run the game once to generate the settings, then should be able to edit it in Config! (Set "Disable Motion Sway" to "false", then leave "Motion Sway Intensity" at 1 or 1.0 for default settings).
