### ISSUE TITLE
terminal bug

### ISSUE THREAD

**Issue by FireNinja7365** [j-red/LethalCompany-RemoveMotionSway#8]
when i open the terminal in game the log gets spammed with this error

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
j_red.Patches.PlayerControllerBPatch.LateUpdatePatch (GameNetcodeStuff.PlayerControllerB& __instance) (at <7db89e02755f403c83278dd71eff7a28>:IL_020B)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::LateUpdate>(GameNetcodeStuff.PlayerControllerB)

**Comment by j-red** [comment]
I'm able to replicate this, not quite sure what causes it yet. Does it seem to have an effect besides logging to the console (i.e. does it cause anything else to glitch or slow down)?

I'll keep an eye out for this and see if there's a fix. Thanks for reporting it!

**Comment by j-red** [comment]
This has been resolved as of v1.2.3, available on the releases tab and will be available on Thunderstore when their cache refreshes in a few hours!
