### ISSUE TITLE
Allow toggling Visor

### ISSUE THREAD

**Issue by KryptoSynth** [j-red/LethalCompany-RemoveMotionSway#9]
I only need the FOV functionality so would like if the visor could be toggled back on. (I use the Immersive Visor mod.)

I would use the FOV Adjust mod but it makes the visor cast a distractingly large shadow.

**Comment by j-red** [comment]
A config option to re-enable the visor has been added in #10 and will be pushed out to Thunderstore and the Releases section shortly.
